name: CI

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run lint
        run: bun nx run-many --target=lint --parallel=3
      - name: Run tests
        run: bun nx run-many --target=test --parallel=3 --ci --code-coverage --skip-cache
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: self-hosted
    needs: test-and-lint
    env:
      HAQQ_STORYBLOK_ACCESS_TOKEN: ${{ secrets.HAQQ_STORYBLOK_ACCESS_TOKEN }}
      ISLAMIC_STORYBLOK_ACCESS_TOKEN: ${{ secrets.ISLAMIC_STORYBLOK_ACCESS_TOKEN }}
      FALCONER_ENDPOINT: ${{ secrets.FALCONER_ENDPOINT }}
      TURNSTILE_SITEKEY: ${{ secrets.TURNSTILE_SITEKEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup dependencies
        run: bun install
      - name: Build
        run: bun nx run-many --target=build --parallel=3
