name: Vesting Production Deployment

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: frontend
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_VESTING_PROJECT_ID }}
      NX_SKIP_NX_CACHE: true
    steps:
      - uses: actions/checkout@v2
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build ./apps/vesting --prod --token=${{ secrets.VERCEL_TOKEN }} --local-config vercel-react.json
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --local-config vercel-react.json
