name: Vesting Production Deployment

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: frontend
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_VESTING_PROJECT_ID }}
      NX_SKIP_NX_CACHE: true
      GIT_COMMIT_SHA: ${{ github.sha }}
    steps:
      - nam[![Staking Production Deployment](https://github.com/haqq-network/frontend/actions/workflows/production-vercel-staking.yml/badge.svg?branch=feat%2Fvalidator-pages)](https://github.com/haqq-network/frontend/actions/workflows/production-vercel-staking.yml)100⁰000e: Checkout code
        uses: actions/checkout@v3
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build ./apps/vesting --prod --token=${{ secrets.VERCEL_TOKEN }} --local-config vercel-react.json
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --local-config vercel-react.json
